version: '3.9'

services:

  mysql:
    image: mysql
    container_name: mysql_mediscreen
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: smashed31
    ports:
      - 3307:3306
    volumes:
      - mysql_db:/data/db

  mongodb:
    image: mongo:latest
    container_name: mongodb_mediscreen
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      -   27017:27017
    volumes:
      -   mongodb_db:/data/db

volumes:
  mongodb_db:
  mysql_db: